runtime! archlinux.vim
runtime! debian.vim

set nocompatible
syntax on

set is hls ic sc ai nowrap
set ts=2 sts=2 sw=2 et sr
set wildmenu so=0 secure
" blank,buffers, vv
set ssop=curdir,folds,help,tabpages,winsize,terminal,globals

" clipboard
map! <C-v> <C-r>+
set clipboard=unnamedplus mouse=nvi

" mouse
if has('mouse')
  set mouse=a
  map <MiddleMouse> <C-W>gf
  map <C-MiddleMouse> :q<CR>
  map <space><MiddleMouse> :q!<CR>
  map c<LeftMouse> <C-w><C-]>
endif

" navigation & misc
nmap <space>w :w<CR><C-l>
nmap <space>q :q<CR>
nmap <space>Q :q!<CR>
nmap <space>t :checktime<CR>
for i in range(1,9) | exe "nmap <space>".i." ".i."gt" | endfor
nmap <space>0 10gt
nmap <space>- 11gt
nmap <space>= 12gt
nmap <C-n> :nohl<CR>
nmap zh zH
nmap zl zL

" searching
nmap * "ayiwk/\<<C-r>a\><CR>
vmap * "ayk/<C-r>a<CR>

" tags & grep
nmap tn :tnext<CR>
nmap ts :tselect<CR>
nmap gn :cnext<CR>
nmap gs :clist<CR>

" man
nmap K "ayiw:Man <C-r>a<CR>
fu! UnixManual(which)
    exe "normal :tabe\<CR>:r !man ".a:which."\<CR>ggdd"
    set ft=man
    nmap <buffer> q :q!<CR>
endfu
com! -nargs=1 -complete=shellcmd Man call UnixManual(<f-args>)

com! -nargs=* -complete=dir Grep :grep -rI <args> --exclude=tags --exclude='*~' --exclude='*.swp' --exclude-dir=.git --exclude-dir=node_modules --exclude-dir='venv*'

com! -nargs=0 Chop exe "normal maHmb" | %s/\s*$//g | exe "normal `bzt`a\<C-n>"

" vim evaluation of ''-commands
nmap <space>e yi':<C-v><CR>lh

