" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim
" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim80/vimrc_example.vim or the vim manual
" and configure vim to your own liking!

set nocompatible
syntax on

set is hls ic sc ai nowrap
set ts=2 sts=2 sw=2 et sr
set clipboard=unnamedplus mouse=nvi
set wildmenu

nmap <space>q :q<CR>
nmap <space>w :w<CR>
nmap <space>1 :tabn 1<CR>
nmap <space>2 :tabn 2<CR>
nmap <space>3 :tabn 3<CR>
nmap <space>4 :tabn 4<CR>
nmap <space>5 :tabn 5<CR>
nmap <space>6 :tabn 6<CR>
nmap <space>7 :tabn 7<CR>
nmap <space>8 :tabn 8<CR>
nmap <space>9 :tabn 9<CR>
nmap <space>0 :tabn 10<CR>

nmap <C-n> :nohl<CR>
nmap * "ayiwk/<C-r>a<CR>
vmap * "ayk/<C-r>a<CR>
map! <C-v> <C-r>+
nmap gn :cnext<CR>
nmap tn :tnext<CR>
nmap ts :tselect<CR>
nmap K "ayiw:Man <C-r>a<CR>
fu! UnixManual(which)
    exe "normal :tabe\<CR>:r !man ".a:which."\<CR>ggdd"
    set ft=man
    nmap <buffer> q :q!<CR>
endfu
com! -nargs=1 -complete=shellcmd Man call UnixManual(<f-args>)

com! -nargs=* Grep :grep -rI <args>
