runtime! archlinux.vim
runtime! debian.vim

set nocompatible
syntax on

set is hls ic sc ai nowrap
set ts=2 sts=2 sw=2 et sr
set clipboard=unnamedplus mouse=nvi
set wildmenu so=0 secure
" blank,buffers, vv
set ssop=curdir,folds,help,tabpages,winsize,terminal,globals

nmap <space>q :q<CR>
nmap <space>w :w<CR>
nmap <space>1 :tabn 1<CR>
nmap <space>2 :tabn 2<CR>
nmap <space>3 :tabn 3<CR>
nmap <space>4 :tabn 4<CR>
nmap <space>5 :tabn 5<CR>
nmap <space>6 :tabn 6<CR>
nmap <space>7 :tabn 7<CR>
nmap <space>8 :tabn 8<CR>
nmap <space>9 :tabn 9<CR>
nmap <space>0 :tabn 10<CR>

nmap <C-n> :nohl<CR>
nmap * "ayiwk/\<<C-r>a\><CR>
vmap * "ayk/<C-r>a<CR>
map! <C-v> <C-r>+
nmap gn :cnext<CR>
nmap tn :tnext<CR>
nmap ts :tselect<CR>
nmap K "ayiw:Man <C-r>a<CR>
fu! UnixManual(which)
    exe "normal :tabe\<CR>:r !man ".a:which."\<CR>ggdd"
    set ft=man
    nmap <buffer> q :q!<CR>
endfu
com! -nargs=1 -complete=shellcmd Man call UnixManual(<f-args>)

com! -nargs=* Grep :grep -rI <args>
